global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['host.docker.internal:9090']
    - job_name: 'discovery-server'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'host.docker.internal:8761' ]
    - job_name: 'api-gateway'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'host.docker.internal:4000' ]
    - job_name: 'auth-server'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'host.docker.internal:5500' ]
    - job_name: 'sample-service-1'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'host.docker.internal:8090' ]
    - job_name: 'sample-service-2'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: [ 'host.docker.internal:8091' ]
